[package]
name = "ravatar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.6"
notify = "6.1.1"
sha2 = "0.10.8"
futures = "0.3.30"
image = "0.25.0"
filetime = "0.2.23"
actix-web = "4.5.1"
serde = { version = "1.0.197", features = ["derive"] }
