[package]
name = "ravatar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.6"
notify = "6.1.1"
sha2 = "0.10.8"
futures = "0.3.30"
image = "0.25.1"
filetime = "0.2.23"
actix-web = "4.7.0"
serde = { version = "1.0.203", features = ["derive"] }
env_logger = "0.11.3"
rayon = "1.10.0"
anyhow = "1.0.86"
log = "0.4.21"
rand = "0.8.5"
ldap3 = "0.11.4"
url = "2.5.0"
