replicaCount: 2

image:
  repository: ghcr.io/reschandreas/ravatar
  pullPolicy: IfNotPresent

ravatar:
  prefix: "/avatar"
  host: "0.0.0.0"
  imageExtension: "png"
  mmExtension: "png"
  defaultFormat: "square"
  port: 8080
  rawImagesPath: "/raw"
  generatedImagesPath: "/images"
  logLevel: "info"
  offerOriginalDimensions: false
  offerFaceCenteredImage: false
  ldap:
    enabled: false


imagePullSecrets: [ ]
nameOverride: "ravatar"
fullnameOverride: "ravatar"

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext:
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations: { }
  hosts:
    - host: ravatar.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

dataSource:
  storageClassName: ""
  mountPath: /raw

resizedImages:
  storageClassName: ""
  mountPath: /images
