replicaCount: 2

image:
  repository: ghcr.io/reschandreas/ravatar
  pullPolicy: IfNotPresent
  tag: nightly

imagePullSecrets: [ ]
nameOverride: "ravatar"
fullnameOverride: "ravatar"

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext:
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations: { }
  hosts:
    - host: ravatar.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

resources: { }

livenessProbe:
  httpGet:
    path: /healthz
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

dataSource:
  storageClassName: ""
  mountPath: /raw

nodeSelector: { }

tolerations: [ ]

affinity: { }
