apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ravatar.fullname" . }}
  labels:
    {{- include "ravatar.labels" . | nindent 4 }}
spec:
  {{- if hasKey .Values "autoscaling" }}
    {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
    {{- end }}
  {{- else  }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ravatar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ravatar.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ravatar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{ if or .Values.ravatar.offerFaceCenteredImage (eq .Values.ravatar.defaultFormat "center") }}-face{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PATH_PREFIX
              value: {{ .Values.ravatar.prefix | default "/avatar" | quote }}
            - name: HOST
              value: {{ .Values.ravatar.host | default "0.0.0.0" | quote }}
            - name: PORT
              value: {{ .Values.ravatar.port | default 8080 | quote }}
            - name: EXTENSION
              value: {{ .Values.ravatar.imageExtension | default "png" | quote }}
            - name: MM_EXTENSION
              value: {{ .Values.ravatar.mmExtension | default "png" | quote }}
            - name: DEFAULT_FORMAT
              value: {{ .Values.ravatar.defaultFormat | default "square" | quote }}
            - name: RAW_PATH
              value: {{ .Values.ravatar.rawImagesPath | default "/raw"| quote }}
            - name: IMAGES_PATH
              value: {{ .Values.ravatar.generatedImagesPath | default "/images" | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.ravatar.logLevel | default "info" | quote }}
            - name: OFFER_ORIGINAL_DIMENSIONS
              value: {{ .Values.ravatar.offerOriginalDimensions | default false | quote }}
            - name: OFFER_FACE_CENTERED_IMAGE
              value: {{ .Values.ravatar.offerFaceCenteredImage | default false | quote }}
            - name: OFFER_PORTRAIT_IMAGE
              value: {{ .Values.ravatar.offerPortraitImage | default false | quote }}
            - name: WATCH_DIRECTORIES
              value: {{ .Values.ravatar.watchDirectories | default true | quote}}
            - name: SCAN_INTERVAL
              value: {{ .Values.ravatar.scanInterval | default 60 | quote}}
            - name: STORAGE_ACCOUNT_URL
              value: {{ .Values.ravatar.storageAccountUrl | default "" | quote }}
            {{ if .Values.ravatar.ldap.enabled }}
            - name: LDAP_URL
              value: {{ .Values.ravatar.ldap.url | quote }}
            - name: LDAP_BIND_USERNAME
              value: {{ .Values.ravatar.ldap.bindUsername | quote }}
            - name: LDAP_BASE_DN
              value: {{ .Values.ravatar.ldap.baseDN | quote }}
            - name: LDAP_SEARCH_FILTER
              value: {{ .Values.ravatar.ldap.searchFilter | quote }}
            - name: LDAP_INPUT_ATTRIBUTE
              value: {{ .Values.ravatar.ldap.inputAttribute | quote }}
            - name: LDAP_TARGET_ATTRIBUTES
              value: {{ .Values.ravatar.ldap.targetAttributes | quote }}
            {{ end }}
            {{ if .Values.envs }}
            {{ toYaml .Values.envs | indent 12 }}
            {{ end }}
          {{- if or .Values.ravatar.ldap.enabled .Values.envFrom }}
          envFrom:
            {{- if and .Values.ravatar.ldap.enabled }}
            - secretRef:
                #key should be LDAP_BIND_PASSWORD
                name: {{ include "ravatar.fullname" . }}-ldap-password
            {{- end }}
            {{- if .Values.envFrom }}
            {{- toYaml .Values.envFrom | nindent 12 }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- else }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-data-source
              mountPath: {{ .Values.dataSource.mountPath }}
            {{- if .Values.resizedImages }}
            - name: {{ .Release.Name }}-resized-images
              mountPath: {{ .Values.ravatar.generatedImagesPath }}
            {{- end }}
            {{ if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: {{ .Release.Name }}-data-source
          persistentVolumeClaim:
            claimName: {{ include "ravatar.fullname" . }}-data-source
        {{- if .Values.resizedImages }}
        - name: {{ .Release.Name }}-resized-images
          persistentVolumeClaim:
            claimName: {{ include "ravatar.fullname" . }}-resized-images
        {{- end }}
        {{ if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.affinity }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}