apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ravatar.fullname" . }}-data-source
  labels:
    {{- include "ravatar.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
    {{- if .Values.dataSource.storageClassName }}
  storageClassName: {{ .Values.dataSource.storageClassName | quote }}
    {{- end }}
  {{- with .Values.dataSource.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}