on: [push]

name: tests

jobs:
  check:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.31.4'
          args: '-- --test-threads 1'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4.6.0
        with:
          name: code-coverage-report
          path: cobertura.xml